# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TwitterLogin' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for TwitterLogin
  pod 'TwitterKit'

  target 'TwitterLoginTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'TwitterLogin-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for TwitterLogin-tvOS

  target 'TwitterLogin-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
